// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0
// source: hello.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FirstClient is the client API for First service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirstClient interface {
	SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type firstClient struct {
	cc grpc.ClientConnInterface
}

func NewFirstClient(cc grpc.ClientConnInterface) FirstClient {
	return &firstClient{cc}
}

func (c *firstClient) SayHello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/helloworld.First/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirstServer is the server API for First service.
// All implementations must embed UnimplementedFirstServer
// for forward compatibility
type FirstServer interface {
	SayHello(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFirstServer()
}

// UnimplementedFirstServer must be embedded to have forward compatible implementations.
type UnimplementedFirstServer struct {
}

func (UnimplementedFirstServer) SayHello(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedFirstServer) mustEmbedUnimplementedFirstServer() {}

// UnsafeFirstServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirstServer will
// result in compilation errors.
type UnsafeFirstServer interface {
	mustEmbedUnimplementedFirstServer()
}

func RegisterFirstServer(s grpc.ServiceRegistrar, srv FirstServer) {
	s.RegisterService(&First_ServiceDesc, srv)
}

func _First_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.First/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstServer).SayHello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// First_ServiceDesc is the grpc.ServiceDesc for First service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var First_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.First",
	HandlerType: (*FirstServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _First_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
